version: '3.9'

services:
  php-app:
    image: ghcr.io/salehnevergiveup/recipe_management_pro:latest
    container_name: Recipe_Management_pro
    env_file:
      - .env
    networks:
      - app-network_pro
    depends_on:
      - db_pro
      - redis_pro

  nginx:
    image: nginx:latest
    container_name: nginx_pro
    ports:
      - "8080:80"
    networks:
      - app-network_pro
    depends_on:
      - php-app
    # You might need volumes here if Nginx needs access to app files
    # volumes:
    #   - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  db_pro:
    image: mysql:8.0
    container_name: db_pro
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: FOOD_PRODUCT
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - db-data:/var/lib/mysql
    networks:
      - app-network_pro

  redis_pro:
    image: redis:7
    container_name: redis_pro
    networks:
      - app-network_pro

networks:
  app-network_pro:

volumes:
  db-data:
